### ISSUE TITLE
Support `safe-init` in Scala 3

### ISSUE THREAD

**Issue by mcanlas** [typelevel/scalac-options#81]
https://docs.scala-lang.org/scala3/reference/other-new-features/safe-initialization.html

**Comment by mcanlas** [comment]
See also https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala#L387C4-L387C4

**Comment by lenguyenthanh** [comment]
Close as done in #85 and #136
